{
	"version": 2026080601,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/playeranim-sheet0.png",
		"images/playeranim-sheet1.png",
		"images/pausedcurtain-sheet0.png",
		"images/popupcurtain-sheet0.png",
		"images/falazapontonem_-sheet0.png",
		"images/falazapontonem_-sheet1.png",
		"images/gwiazdkadozbierania-sheet0.png",
		"images/obstacle_balwan-sheet0.png",
		"images/obstacle_balwan-sheet1.png",
		"images/obstacle_bin-sheet0.png",
		"images/obstacle_bin-sheet1.png",
		"images/obstacle_kula_-sheet0.png",
		"images/obstacle_kula_-sheet1.png",
		"images/obstacle_opony-sheet0.png",
		"images/obstacle_plotek-sheet0.png",
		"images/obstacle_plotek-sheet1.png",
		"images/obstacle_plotek-sheet2.png",
		"images/obstacle_tree-sheet0.png",
		"images/obstacle_tree-sheet1.png",
		"images/obstacle_yeti_-sheet0.png",
		"images/obstacle_yeti_-sheet1.png",
		"images/obstacle_yeti_-sheet2.png",
		"images/ciennarciarza-sheet0.png",
		"images/ciennarciarza-sheet1.png",
		"images/ciennarciarza-sheet2.png",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnplay-sheet0.png",
		"images/btncontinue-sheet0.png",
		"images/btn_arrowleft_blue-sheet0.png",
		"images/btn_arrowleft_blue-sheet1.png",
		"images/btn_arrowright_blue-sheet0.png",
		"images/btn_arrowright_blue-sheet1.png",
		"images/btn_back_blue-sheet0.png",
		"images/btn_back_blue-sheet1.png",
		"images/btnhats-sheet0.png",
		"images/btn_nextgogle_out-sheet0.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundunmute-sheet0.png",
		"images/btnclose-sheet0.png",
		"images/btnpause-sheet0.png",
		"images/btnoneplayer-sheet0.png",
		"images/btnoneplayer-sheet1.png",
		"images/btntwoplayers-sheet0.png",
		"images/btntwoplayers-sheet1.png",
		"images/pausecurtain.png",
		"images/preloaderfont2.png",
		"images/pricetf.png",
		"images/board-sheet0.png",
		"images/highscorelabel-sheet0.png",
		"images/htp_touch_-sheet0.png",
		"images/flashscreen-sheet0.png",
		"images/scorepanel-sheet0.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/unlocked-sheet0.png",
		"images/skala_-sheet0.png",
		"images/animacjawalnieciawprzeszkode_-sheet0.png",
		"images/sniegspodnart_-sheet0.png",
		"images/slady_proste-sheet0.png",
		"images/slady_proste-sheet1.png",
		"images/slady_zakret-sheet0.png",
		"images/slady_zakret-sheet1.png",
		"images/tlodogameplaya-sheet0.png",
		"images/slady_prostek-sheet0.png",
		"images/obstacle_plotekcien-sheet0.png",
		"images/game_bg-sheet0.png",
		"images/animacjarozwaleniagifta-sheet0.png",
		"images/animacjarozwaleniagifta-sheet1.png",
		"images/animacjarozwaleniagifta-sheet2.png",
		"images/buyanimbonusmedal-sheet0.png",
		"images/pausedicon-sheet0.png",
		"images/start_place-sheet0.png",
		"images/cienyeti_-sheet0.png",
		"images/logo-sheet0.png",
		"images/playerranktf.png",
		"images/btntryagain-sheet0.png",
		"images/won-sheet0.png",
		"images/playerlabel-sheet0.png",
		"images/letterboxframe-sheet0.png",
		"images/sciezkarowerowa-sheet0.png",
		"images/chodnik-sheet0.png",
		"images/scorefont2.png",
		"images/ui_panel_najlepszywynik-sheet0.png",
		"images/ui_panel_twojwynik-sheet0.png",
		"images/ui_graskonczona-sheet0.png",
		"images/ui_tapnijbygracdalejpng-sheet0.png",
		"images/submit_gratsy-sheet0.png",
		"images/submit_email-sheet0.png",
		"images/submit_nazwisko-sheet0.png",
		"images/submit_btn-sheet0.png",
		"images/tap_-sheet0.png",
		"images/tap_-sheet1.png",
		"images/citybg-sheet0.png",
		"images/postacnacoverze-sheet0.png",
		"images/baloncover-sheet0.png",
		"images/imie-sheet0.png",
		"images/tekstformularz-sheet0.png",
		"images/opiscover-sheet0.png",
		"images/loadinganim-sheet0.png",
		"media/checkpoint_02.m4a",
		"media/checkpoint_02.ogg",
		"media/bear roar 03.m4a",
		"media/bear roar 03.ogg",
		"media/scoring 02.m4a",
		"media/scoring 02.ogg",
		"media/snowball 01.m4a",
		"media/snowball 01.ogg",
		"media/tap sound 02 .m4a",
		"media/tap sound 02 .ogg",
		"media/yeti 01.m4a",
		"media/yeti 01.ogg",
		"media/pie_07.m4a",
		"media/pie_07.ogg",
		"media/direction swoosh original .m4a",
		"media/direction swoosh original .ogg",
		"media/groovy ski.m4a",
		"media/groovy ski.ogg",
		"media/power-up 1.m4a",
		"media/power-up 1.ogg",
		"media/powerup4.m4a",
		"media/powerup4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"local-leaderboard.js",
		"lz-string.min.js"
	]
}